# Generated by Django 4.2.4 on 2023-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01_tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab01_tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('tipo_operacion', models.CharField(max_length=20)),
                ('resultado', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
